/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type NewsItem = {
  _id: string;
  _type: "newsItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  excerpt?: string;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clientName?: string;
  quote?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  rotation?: number;
  positionLeft?: number;
  positionTop?: number;
  behindText?: boolean;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  order?: number;
};

export type Portfolio = {
  _id: string;
  _type: "portfolio";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  client?: string;
  year?: number;
  categories?: Array<string>;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  projectUrl?: string;
  tall?: boolean;
  order?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroDescription?: string;
  heroBgDesktop?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroBgMobile?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  aboutPortrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  aboutText?: string;
  fullBleedPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | NewsItem
  | SanityImageCrop
  | SanityImageHotspot
  | Testimonial
  | Service
  | Portfolio
  | Slug
  | Homepage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_type == "homepage" && _id == "homepage"][0] {    heroDescription,    "heroBgDesktop": heroBgDesktop.asset->url,    "heroBgMobile": heroBgMobile.asset->url,    "aboutPortrait": aboutPortrait.asset->url,    aboutText,    "fullBleedPhoto": fullBleedPhoto.asset->url,  }
export type HOMEPAGE_QUERY_RESULT = {
  heroDescription: string | null;
  heroBgDesktop: string | null;
  heroBgMobile: string | null;
  aboutPortrait: string | null;
  aboutText: string | null;
  fullBleedPhoto: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: PORTFOLIO_QUERY
// Query: *[_type == "portfolio"] | order(order asc) {    _id,    title,    "slug": slug.current,    categories,    "coverImageUrl": coverImage.asset->url,    tall,  }
export type PORTFOLIO_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  categories: Array<string> | null;
  coverImageUrl: string | null;
  tall: boolean | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(order asc) {    _id,    name,    description,    "imageUrl": image.asset->url,  }
export type SERVICES_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  description: string | null;
  imageUrl: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"] {    _id,    clientName,    quote,    "logoUrl": logo.asset->url,    rotation,    positionLeft,    positionTop,    behindText,  }
export type TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  clientName: string | null;
  quote: string | null;
  logoUrl: string | null;
  rotation: number | null;
  positionLeft: number | null;
  positionTop: number | null;
  behindText: boolean | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: NEWS_QUERY
// Query: *[_type == "newsItem"] | order(order asc) {    _id,    "imageUrl": image.asset->url,    excerpt,  }
export type NEWS_QUERY_RESULT = Array<{
  _id: string;
  imageUrl: string | null;
  excerpt: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "homepage" && _id == "homepage"][0] {\n    heroDescription,\n    "heroBgDesktop": heroBgDesktop.asset->url,\n    "heroBgMobile": heroBgMobile.asset->url,\n    "aboutPortrait": aboutPortrait.asset->url,\n    aboutText,\n    "fullBleedPhoto": fullBleedPhoto.asset->url,\n  }\n': HOMEPAGE_QUERY_RESULT;
    '\n  *[_type == "portfolio"] | order(order asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    categories,\n    "coverImageUrl": coverImage.asset->url,\n    tall,\n  }\n': PORTFOLIO_QUERY_RESULT;
    '\n  *[_type == "service"] | order(order asc) {\n    _id,\n    name,\n    description,\n    "imageUrl": image.asset->url,\n  }\n': SERVICES_QUERY_RESULT;
    '\n  *[_type == "testimonial"] {\n    _id,\n    clientName,\n    quote,\n    "logoUrl": logo.asset->url,\n    rotation,\n    positionLeft,\n    positionTop,\n    behindText,\n  }\n': TESTIMONIALS_QUERY_RESULT;
    '\n  *[_type == "newsItem"] | order(order asc) {\n    _id,\n    "imageUrl": image.asset->url,\n    excerpt,\n  }\n': NEWS_QUERY_RESULT;
  }
}
